(function () {
  "use strict";

  var globalRule = "Use prioritariamente os dados já cadastrados do jogador, a temporada atual, o calendário, as partidas, os personagens, as relações, as notícias, as finanças e os acontecimentos recentes. Não invente resultados, estatísticas ou acontecimentos que deveriam estar cadastrados. Quando criar conteúdo narrativo novo, mantenha continuidade com tudo que já existe. Quando a ação gerar dados relevantes, retorne também as informações estruturadas necessárias para atualizar as áreas correspondentes do sistema.";

  function shortcut(id, label, group, prompt) {
    return Object.freeze({ id: id, label: label, group: group, prompt: prompt });
  }

  var shortcuts = [
    shortcut("REGISTER_MATCH", "Registrar nova partida", "PARTIDAS E CARREIRA", "Vou enviar os acontecimentos de uma partida. Analise todas as informações, identifique competição, adversário, placar, titularidade, minutos jogados, gols, assistências, cartões, substituições, acontecimentos importantes e participação do jogador. Registre a partida no calendário esportivo e na temporada atual. Atualize automaticamente partidas disputadas, gols, assistências, títulos ou classificações quando aplicável. Não invente estatísticas que eu não informar. Depois, faça um resumo narrativo completo da partida e destaque os acontecimentos que terão repercussão futura."),
    shortcut("QUICK_RESULT", "Registrar resultado rápido", "PARTIDAS E CARREIRA", "Vou informar apenas o resultado e os principais acontecimentos de uma partida. Transforme essas informações em um registro completo e organizado, atualizando calendário, temporada atual, gols, assistências, partidas e competição. Separe claramente fatos confirmados de informações não fornecidas."),
    shortcut("PRE_MATCH", "Pré-jogo", "PARTIDAS E CARREIRA", "Use o calendário esportivo e os acontecimentos recentes para criar a cobertura completa do próximo jogo do jogador. Inclua contexto da competição, momento dos dois times, provável importância da partida, pressão sobre o jogador, possíveis duelos individuais, declarações da imprensa e principais narrativas antes do jogo. Não determine o resultado."),
    shortcut("PRE_MATCH_LOCKER", "Vestiário antes do jogo", "PARTIDAS E CARREIRA", "Inicie um roleplay no vestiário antes da próxima partida registrada no calendário. Use treinador, companheiros e personagens cadastrados quando apropriado. Crie diálogos naturais, tensão competitiva, instruções táticas e interações pessoais. Termine deixando espaço para o usuário decidir o que o jogador fará ou responderá."),
    shortcut("HALF_TIME", "Intervalo da partida", "PARTIDAS E CARREIRA", "Faça um roleplay do intervalo usando somente os acontecimentos da partida que eu já informei. O treinador deve comentar problemas e oportunidades reais do primeiro tempo, companheiros podem interagir e o jogador deve ter liberdade para responder. Não determine acontecimentos do segundo tempo."),
    shortcut("POST_MATCH_LOCKER", "Pós-jogo no vestiário", "PARTIDAS E CARREIRA", "Crie o roleplay imediatamente após a partida mais recente. Considere resultado, atuação individual, gols, erros, rivalidades, importância da competição e personalidade dos personagens cadastrados. Mostre reações coerentes de treinador, companheiros e staff sem substituir decisões do jogador."),
    shortcut("ANALYZE_PERFORMANCE", "Analisar minha atuação", "PARTIDAS E CARREIRA", "Analise exclusivamente a partida mais recente registrada e faça uma avaliação detalhada da atuação do jogador: impacto ofensivo, decisões, movimentação, participação nos gols, erros, momentos decisivos, influência sobre o resultado e consequências para a temporada. Diferencie fatos registrados de interpretação."),
    shortcut("SEASON_SUMMARY", "Resumo da temporada", "PARTIDAS E CARREIRA", "Use todos os dados registrados da temporada atual e produza um panorama completo: partidas, gols, assistências, títulos, desempenho por competição, evolução ao longo do ano, jogos mais importantes, melhores sequências, momentos ruins, rivalidades, acontecimentos fora do campo e situação atual da carreira."),

    shortcut("FYX_HEADLINES", "Ver manchetes atuais", "FYX NEWS", "Use os acontecimentos registrados mais recentes para criar a edição atual da FYX NEWS. Gere uma manchete principal forte e várias manchetes secundárias de veículos diferentes. Inclua imprensa esportiva, televisão, jornais, portais e jornalistas quando apropriado. Cada manchete deve refletir fatos existentes e perspectivas diferentes. Retorne também os campos necessários para registrar essas notícias na FYX NEWS, identificando data, assunto, importância, evento relacionado e manchete principal."),
    shortcut("MATCH_COVERAGE", "Cobertura completa da última partida", "FYX NEWS", "Crie a cobertura jornalística completa da partida mais recente registrada. Inclua manchete principal, matérias secundárias, análise tática, avaliação da atuação do jogador, repercussão do resultado, críticas, elogios, personagens citados e possíveis consequências. Produza conteúdo suficiente para preencher a sessão FYX NEWS referente a essa partida."),
    shortcut("PRESS_OPINIONS", "O que a imprensa está dizendo?", "FYX NEWS", "Simule diferentes veículos e jornalistas comentando os acontecimentos recentes da carreira. Não faça todos concordarem. Inclua elogios, críticas, análises neutras, opiniões polêmicas e debates sobre o jogador."),
    shortcut("SPORT_CONTROVERSY", "Criar polêmica esportiva", "FYX NEWS", "Analise acontecimentos recentes já registrados e identifique se existe algum elemento capaz de gerar debate ou controvérsia esportiva. Se existir, desenvolva a repercussão da imprensa de maneira realista. Se não existir base suficiente, informe que não há polêmica relevante em vez de inventar uma."),
    shortcut("EXCLUSIVE_INTERVIEW", "Entrevista exclusiva", "FYX NEWS", "Inicie uma entrevista individual com um jornalista relevante sobre os acontecimentos atuais da carreira. Faça uma pergunta por vez, adapte as perguntas às minhas respostas e explore temas interessantes naturalmente. Minhas declarações poderão gerar manchetes e devem ser armazenáveis na FYX NEWS."),

    shortcut("PRESS_CONFERENCE", "Iniciar coletiva", "COLETIVAS", "Inicie uma coletiva de imprensa interativa relacionada ao acontecimento esportivo mais recente. Interprete vários repórteres de veículos e estilos diferentes. Faça apenas uma pergunta por vez e espere minha resposta. Reaja às minhas respostas, permita perguntas de acompanhamento e faça a coletiva evoluir naturalmente. Não responda pelo jogador. Minhas declarações importantes devem ser identificadas como possíveis manchetes para a FYX NEWS."),
    shortcut("PRE_MATCH_PRESS", "Coletiva pré-jogo", "COLETIVAS", "Inicie uma coletiva antes da próxima partida do calendário. Os jornalistas devem perguntar sobre adversário, momento da equipe, expectativas, pressão, companheiros, treinador, números recentes e possíveis narrativas existentes. Faça uma pergunta por vez."),
    shortcut("POST_MATCH_PRESS", "Coletiva pós-jogo", "COLETIVAS", "Inicie uma coletiva baseada exclusivamente na partida mais recente. Jornalistas devem abordar os momentos realmente ocorridos, resultado, atuação individual, decisões controversas, gols, erros e declarações anteriores quando relevantes. Faça uma pergunta por vez e permita repercussão das minhas respostas."),
    shortcut("TENSE_PRESS", "Coletiva tensa", "COLETIVAS", "Inicie uma coletiva especialmente agressiva e desafiadora usando uma polêmica real já registrada. Alguns jornalistas podem insistir, questionar contradições ou provocar o jogador, mas mantenha comportamento profissional e plausível. Faça uma pergunta por vez."),

    shortcut("SOCIAL_MEDIA", "Ver as redes sociais", "REDES SOCIAIS", "Crie a repercussão das redes sociais baseada nos acontecimentos mais recentes registrados. Inclua posts de torcedores, críticos, jornalistas, influenciadores, páginas esportivas, memes, fan accounts e comentários internacionais quando fizer sentido. Gere também hashtags e trending topics. Não apresente apenas elogios; mostre opiniões variadas. Retorne as informações necessárias para registrar tudo na sessão REDES SOCIAIS."),
    shortcut("TRENDING_TOPICS", "Trending topics", "REDES SOCIAIS", "Mostre os principais assuntos em alta relacionados ao jogador neste momento. Para cada trending topic, explique rapidamente por que está em alta e qual acontecimento registrado provocou a tendência."),
    shortcut("FAN_COMMENTS", "Comentários dos torcedores", "REDES SOCIAIS", "Gere uma grande seleção de comentários realistas de torcedores sobre o acontecimento mais recente. Misture fãs, rivais, neutros, haters, páginas de estatísticas e torcedores do próprio clube."),
    shortcut("ROUND_MEMES", "Memes da rodada", "REDES SOCIAIS", "Com base na partida ou acontecimento recente, crie descrições de memes, piadas e posts virais que estariam circulando nas redes sociais. Não invente acontecimentos que não ocorreram."),
    shortcut("FANDOM", "Ver meu fandom", "REDES SOCIAIS", "Mostre a atividade recente dos fan clubs e fan accounts relacionados ao jogador: campanhas, montagens, elogios, discussões, teorias, apelidos, hashtags e reações emocionais aos acontecimentos recentes."),

    shortcut("GOSSIP", "Ver as fofocas", "FOFOCAS E VIDA PESSOAL", "Use os acontecimentos pessoais mais recentes registrados e gere a repercussão da imprensa de celebridades, fan clubs, paparazzi, redes sociais e fóruns. Inclua rumores, comentários, teorias e trending topics. Diferencie claramente fatos confirmados, rumores plausíveis e especulações dos fãs. Retorne os dados necessários para registrar na sessão FOFOCAS."),
    shortcut("PERSONAL_PUBLIC_TALK", "O que estão falando sobre minha vida pessoal?", "FOFOCAS E VIDA PESSOAL", "Mostre diferentes conversas públicas sobre a vida pessoal do jogador usando somente informações e acontecimentos cadastrados como ponto de partida. Inclua fãs, haters, tabloides, jornalistas e comunidades online."),
    shortcut("PAPARAZZI", "Paparazzi", "FOFOCAS E VIDA PESSOAL", "Crie uma situação narrativa plausível envolvendo imprensa ou paparazzi baseada no local e atividade atual do jogador. Não determine automaticamente consequências graves e não revele informações secretas que nenhum personagem ou veículo poderia conhecer."),
    shortcut("RELATIONSHIP_RUMORS", "Rumores de relacionamento", "FOFOCAS E VIDA PESSOAL", "Analise as interações públicas recentes do jogador com personagens cadastrados e mostre quais rumores de relacionamento poderiam surgir naturalmente. Diferencie fatos, interpretações públicas e especulações."),
    shortcut("REACT_GOSSIP", "Reagir a uma fofoca", "FOFOCAS E VIDA PESSOAL", "Mostre a fofoca ou rumor recente mais relevante e permita que eu escolha como reagir: ignorar, responder publicamente, conversar com alguém em particular, falar com assessoria ou tomar outra ação. Não escolha por mim."),

    shortcut("MEET_SOMEONE", "Encontrar alguém", "ROLEPLAY COM PERSONAGENS", "Use personagens cadastrados, localização, agenda e relações atuais para iniciar uma interação plausível com alguém que poderia estar presente naquele momento. Respeite personalidade, histórico, intimidade, conflitos e informações que cada personagem realmente conhece."),
    shortcut("TALK_CHARACTER", "Conversar com [personagem]", "ROLEPLAY COM PERSONAGENS", "Personagem: [escreva o nome]. Inicie um roleplay privado entre o jogador e o personagem escolhido. Consulte a ficha do personagem, o histórico da relação e os acontecimentos recentes. Interprete somente o personagem e o ambiente; nunca escolha falas, sentimentos ou decisões do jogador."),
    shortcut("MESSAGE_CHARACTER", "Mandar mensagem para alguém", "ROLEPLAY COM PERSONAGENS", "Personagem: [escreva o nome]. Abra uma conversa por mensagens com o personagem escolhido. Respeite o estilo de escrita, a personalidade e o nível de intimidade cadastrados. O personagem deve reagir naturalmente ao contexto atual."),
    shortcut("RESOLVE_ARGUMENT", "Resolver uma discussão", "ROLEPLAY COM PERSONAGENS", "Identifique algum conflito ou tensão existente com um personagem cadastrado e permita iniciar uma conversa para resolver a situação. Não force reconciliação; as consequências devem depender do diálogo."),
    shortcut("FRIENDS_TIME", "Passar tempo com amigos", "ROLEPLAY COM PERSONAGENS", "Crie um roleplay casual usando amigos cadastrados que estejam plausivelmente disponíveis. Pode envolver restaurante, videogame, conversa, passeio, festa, viagem curta ou outra atividade coerente com agenda e localização."),

    shortcut("REST_HOME", "Descansar em casa", "VIDA FORA DO GRAMADO", "Inicie uma cena tranquila na residência do jogador. Considere horário, agenda, acontecimentos recentes, cansaço, personagens que poderiam estar presentes e mensagens ou acontecimentos plausíveis. Não transforme necessariamente a cena em um grande evento."),
    shortcut("DINNER_OUT", "Sair para jantar", "VIDA FORA DO GRAMADO", "Crie um roleplay de uma saída para jantar. Permita escolher companhia quando necessário e use personagens cadastrados. Considere possibilidade de fãs, imprensa ou acontecimentos espontâneos sem forçar eventos."),
    shortcut("PARTY_OUT", "Ir a uma festa", "VIDA FORA DO GRAMADO", "Crie uma experiência de festa interativa com personagens cadastrados e possíveis convidados plausíveis. Apresente ambiente, conversas, situações sociais e escolhas. O jogador mantém controle total sobre suas ações."),
    shortcut("BIRTHDAY_PARTY", "Festa de aniversário", "VIDA FORA DO GRAMADO", "Organize um roleplay completo de aniversário baseado na data, relações e personagens cadastrados. Determine convidados plausíveis, presentes, mensagens públicas, encontros, possíveis surpresas e repercussão social. Preserve segredos e relações privadas."),
    shortcut("DAY_OFF", "Dia de folga", "VIDA FORA DO GRAMADO", "Use calendário, jogos, treinos e compromissos para criar um dia de folga plausível. Apresente algumas possibilidades de atividades sem decidir automaticamente o que o jogador fará."),
    shortcut("FREE_NIGHT", "Noite livre", "VIDA FORA DO GRAMADO", "Considere a agenda do jogador e crie possibilidades realistas para aproveitar uma noite sem compromissos. Podem envolver personagens cadastrados, descanso, entretenimento ou vida social."),

    shortcut("PERSONAL_TRAINER", "Treinar com treinador pessoal", "TREINOS", "Inicie uma sessão interativa com o treinador pessoal cadastrado. Considere condição física, objetivos atuais, partidas recentes e características do treinador. Defina objetivo da sessão e desafios, mas não determine automaticamente sucesso ou evolução."),
    shortcut("CLUB_TRAINING", "Treino do clube", "TREINOS", "Crie o treino do time usando calendário, treinador da equipe, companheiros cadastrados, próximo adversário e situação atual da temporada. Inclua exercícios, interações, disputas por posição e observações táticas plausíveis."),
    shortcut("INDIVIDUAL_TRAINING", "Treino individual", "TREINOS", "Pergunte ou identifique qual atributo ou fundamento o jogador quer desenvolver e crie uma sessão específica para isso. Registre resultados relevantes somente quando eles acontecerem durante o roleplay."),
    shortcut("COACH_CHALLENGE", "Desafio do treinador", "TREINOS", "O treinador pessoal deve criar um desafio específico baseado nos pontos fortes, fraquezas e evolução recente do jogador. O desafio precisa ter objetivo, critérios claros de sucesso e consequências narrativas plausíveis."),
    shortcut("PROGRESS_ANALYSIS", "Analisar evolução", "TREINOS", "Compare os treinos e partidas registrados ao longo da temporada para identificar evolução técnica, física e mental. Não atribua melhorias que não tenham base nos dados ou acontecimentos cadastrados."),

    shortcut("AGENDA", "Ver minha agenda", "AGENDA E CALENDÁRIO", "Mostre a agenda atual do jogador em ordem cronológica usando calendário esportivo e compromissos pessoais cadastrados. Destaque próxima partida, treinos, eventos, viagens, compromissos comerciais, datas importantes e períodos livres."),
    shortcut("TODAY_AGENDA", "O que tenho hoje?", "AGENDA E CALENDÁRIO", "Consulte a agenda do jogador e apresente os compromissos do dia atual em ordem de horário. Informe também períodos livres disponíveis para roleplay."),
    shortcut("PLAN_DAY", "Planejar meu dia", "AGENDA E CALENDÁRIO", "Use todos os compromissos cadastrados para criar uma programação plausível para o dia, preservando os horários obrigatórios e sugerindo atividades opcionais nos períodos livres."),
    shortcut("NEXT_APPOINTMENT", "Avançar para o próximo compromisso", "AGENDA E CALENDÁRIO", "Identifique o próximo evento cronológico cadastrado e avance a narrativa até ele. Faça apenas um resumo breve do intervalo de tempo e inicie a cena quando chegar ao compromisso."),
    shortcut("ADVANCE_DAY", "Avançar um dia", "AGENDA E CALENDÁRIO", "Avance a simulação até o próximo dia, preservando continuidade. Antes de avançar, processe somente acontecimentos inevitáveis já cadastrados na agenda. Não invente resultados de partidas futuras."),

    shortcut("FINANCE_OVERVIEW", "Ver minhas finanças", "BANCO, CONTRATOS E PATRIMÔNIO", "Analise os dados do banco do jogador e apresente saldo, receitas recentes, despesas recentes, maiores categorias de gastos e alterações relevantes no patrimônio. Não invente valores ausentes."),
    shortcut("REGISTER_PURCHASE", "Registrar uma compra", "BANCO, CONTRATOS E PATRIMÔNIO", "Vou informar uma compra realizada pelo jogador. Registre descrição, categoria, valor e data no banco. Atualize o saldo correspondente e avalie se a compra merece alguma consequência narrativa ou notícia."),
    shortcut("MONTH_STATEMENT", "Extrato do mês", "BANCO, CONTRATOS E PATRIMÔNIO", "Faça um resumo financeiro do mês atual usando somente transações registradas. Mostre entradas, saídas, saldo líquido e principais gastos."),
    shortcut("CONTRACTS", "Ver contratos", "BANCO, CONTRATOS E PATRIMÔNIO", "Mostre os contratos esportivos e comerciais cadastrados do jogador, valores conhecidos, duração, obrigações, bônus e datas importantes."),
    shortcut("COMMERCIAL_OFFER", "Receber proposta comercial", "BANCO, CONTRATOS E PATRIMÔNIO", "Crie uma proposta comercial plausível considerando fama, momento da carreira, contratos existentes e perfil público do jogador. Apresente marca, campanha, duração, valores e exigências para que eu possa aceitar, rejeitar ou negociar."),
    shortcut("NEGOTIATE_CONTRACT", "Negociar contrato", "BANCO, CONTRATOS E PATRIMÔNIO", "Inicie uma negociação interativa de contrato baseada em uma proposta existente. Interprete agente, clube, patrocinador ou representante envolvido e permita contrapropostas. Não aceite termos pelo jogador."),

    shortcut("ACHIEVEMENTS", "Ver minhas conquistas", "CONQUISTAS E HISTÓRICO", "Mostre o Hall de Troféus completo do jogador usando somente conquistas registradas. Separe títulos coletivos, prêmios individuais, recordes e outras conquistas relevantes."),
    shortcut("REGISTER_ACHIEVEMENT", "Registrar conquista", "CONQUISTAS E HISTÓRICO", "Analise o acontecimento esportivo informado e determine se ele gera algum título, prêmio, recorde ou conquista que deva ser registrado no Hall de Troféus. Nunca registre algo sem base suficiente."),
    shortcut("REMEMBER_MOMENT", "Relembrar um grande momento", "CONQUISTAS E HISTÓRICO", "Escolha um acontecimento importante já registrado na carreira e faça uma retrospectiva narrativa com contexto, impacto, repercussão e consequências que ele teve posteriormente."),
    shortcut("COMPARE_SEASONS", "Comparar temporadas", "CONQUISTAS E HISTÓRICO", "Compare temporadas cadastradas do jogador considerando partidas, gols, assistências, títulos, desempenho por competição e acontecimentos relevantes fora do gramado."),
    shortcut("CAREER_TIMELINE", "Linha do tempo da carreira", "CONQUISTAS E HISTÓRICO", "Crie uma linha do tempo cronológica da carreira usando exclusivamente acontecimentos registrados: clubes, temporadas, partidas marcantes, títulos, recordes, transferências, relações importantes e momentos da vida pessoal."),

    shortcut("FOOTBALL_WORLD", "O que está acontecendo no futebol?", "MUNDO VIVO", "Crie um panorama do universo esportivo atual além do jogador. Utilize competições, clubes, atletas, resultados e acontecimentos já cadastrados quando existirem. Desenvolva notícias paralelas plausíveis sobre outros jogadores e clubes sem relacionar tudo ao protagonista."),
    shortcut("CLUB_NEWS", "Notícias do meu clube", "MUNDO VIVO", "Mostre acontecimentos recentes envolvendo o clube do jogador: treinador, companheiros, diretoria, transferências, lesões, rumores, disputas por posição e ambiente interno. Nem todas as notícias precisam envolver o jogador."),
    shortcut("RIVAL_NEWS", "Notícias dos rivais", "MUNDO VIVO", "Mostre acontecimentos relevantes envolvendo clubes e jogadores rivais na temporada atual. Priorize fatos que possam afetar competições ou histórias futuras."),
    shortcut("TRANSFER_MARKET", "Mercado da bola", "MUNDO VIVO", "Crie um boletim do mercado de transferências do universo atual. Inclua negociações, rumores e movimentações envolvendo diversos clubes. Diferencie transferências confirmadas de rumores."),
    shortcut("ROUND_RESULTS", "Resultados da rodada", "MUNDO VIVO", "Mostre os resultados relevantes da rodada da competição atual, incluindo outros clubes, classificação e impacto esportivo. Não altere resultados previamente cadastrados."),

    shortcut("SURPRISE_ME", "Surpreenda-me", "MODO CARREIRA VIVO", "Analise calendário, relações, carreira, vida pessoal e acontecimentos recentes e crie um acontecimento espontâneo plausível. Pode ser esportivo, profissional, social ou pessoal. Não contradiga dados existentes, não revele segredos impossíveis de conhecer e não force decisões do jogador."),
    shortcut("ANYTHING_HAPPENED", "Alguma coisa aconteceu?", "MODO CARREIRA VIVO", "Verifique o contexto atual e apresente acontecimentos novos plausíveis que poderiam ter surgido desde a última interação: mensagens, notícias, convites, acontecimentos do clube ou atualizações pessoais. Evite acontecimentos grandes sem preparação narrativa."),
    shortcut("MESSAGES", "Tenho alguma mensagem?", "MODO CARREIRA VIVO", "Considere personagens cadastrados, relações e acontecimentos recentes e mostre mensagens plausíveis recebidas pelo jogador. Cada personagem deve escrever de acordo com sua personalidade e conhecimento."),
    shortcut("SOMEONE_WANTS_TALK", "Alguém quer falar comigo?", "MODO CARREIRA VIVO", "Analise relações e acontecimentos recentes e identifique personagens que teriam um motivo real para procurar o jogador. Apresente quem está entrando em contato e por quê, sem iniciar automaticamente uma conversa longa."),
    shortcut("RANDOM_EVENT", "Criar acontecimento aleatório", "MODO CARREIRA VIVO", "Gere um acontecimento contextual usando localização, horário, calendário e personagens existentes. Priorize eventos pequenos ou médios que tornem o universo vivo. Eventos extraordinários devem ser raros e possuir justificativa."),
    shortcut("CONTINUE_STORY", "Continuar minha história", "MODO CARREIRA VIVO", "Analise o ponto cronológico atual, os últimos acontecimentos, o calendário, as relações e as histórias em andamento. Continue exatamente do ponto atual, priorizando tramas ainda abertas e acontecimentos próximos. Nunca pule partidas ou eventos importantes sem autorização."),

    shortcut("PRESS_REACTION", "Ver repercussão das minhas declarações", "TRANSIÇÕES", "Analise exclusivamente as declarações que acabei de dar na coletiva. Gere manchetes, cortes de vídeo, comentários de jornalistas, reações de torcedores, trending topics e possíveis reações de personagens cadastrados que tenham motivo para acompanhar a declaração. Atualize FYX NEWS e REDES SOCIAIS quando aplicável.")
  ];

  window.INYFFX_SHORTCUT_GLOBAL_RULE = globalRule;
  window.INYFFX_SHORTCUT_LIBRARY = Object.freeze(shortcuts);
})();
